[auth]
redirect_url="https://medbriefai.streamlit.app/oauth2callback"
cookie_secret="U3I6w9zVfS2#kT@qL7mH^Xe8!bNp5G$d"

[auth.auth0]
domain="dev-bbsmpt1ugvrb1jum.us.auth0.com"
client_id="C5wVvXhmEwvoVtihp35SE0HPKAHf0ane"
client_secret="FSOnP52q9RVFGkZ1BXLizQoDjQHFL7_csy3GsVaq0_5-U9M_YVUQqUVwgImFakJc"
server_metadate_url="dev-bbsmpt1ugvrb1jum.us.auth0.com/.well-known/openid-configuration"
client_kwargs={"prompt"="login"}




[gcp]
gemini_api_key = "AIzaSyCoBAZzNOnd2mKMnyNoxZC83KJVpRVCOVI"